from __future__ import annotations

from dataclasses import replace

import pytest


def _actor():
    from brain.v5.record_envelope import RecordActor

    return RecordActor(actor_type="tool", actor_id="knowledge-review-test", host="pytest")


def _candidate(grounding_pins=()):
    from brain.v5.knowledge_candidates import KnowledgeCandidate

    return KnowledgeCandidate(
        candidate_id="local-algebra-definition",
        content_kinds=("definition",),
        statement="A(O) is generated by observables localized in O.",
        topic_id="qg",
        framework="algebraic QFT",
        regime="continuum local net",
        grounding_pins=tuple(grounding_pins),
    )


def _grounding(ws):
    from brain.v5.models import ReferenceLocationRecord, SourceAssetRecord
    from brain.v5.pinned_record_refs import pin_current_record
    from brain.v5.record_repository import RecordRepository

    repository = RecordRepository(ws, actor=_actor())
    repository.write(
        "source_assets",
        SourceAssetRecord(
            asset_id="haag-book",
            topic_id="qg",
            asset_type="book",
            uri="file:///sources/haag.pdf",
            title="Local Quantum Physics",
            content_hash="a" * 64,
            hash_algorithm="sha256",
        ),
    )
    repository.write(
        "reference_locations",
        ReferenceLocationRecord(
            location_id="haag-local-algebra",
            topic_id="qg",
            connector_id="local-source",
            location_type="page_anchor",
            uri="file:///sources/haag.pdf#page=101",
            label="Local algebra definition",
            source_ref="source_asset:haag-book",
        ),
    )
    return (
        pin_current_record(ws, "source_asset:haag-book"),
        pin_current_record(ws, "reference_location:haag-local-algebra"),
    )


def _checkpoint(ws, candidate, *, verified=True):
    from brain.v5.knowledge_review import knowledge_candidate_hash
    from brain.v5.models import HumanCheckpointRecord
    from brain.v5.pinned_record_refs import PinnedRecordRef
    from brain.v5.record_repository import RecordRepository

    candidate_hash = knowledge_candidate_hash(candidate)
    result = RecordRepository(ws, actor=_actor()).write(
        "checkpoints",
        HumanCheckpointRecord(
            checkpoint_id="knowledge-review-checkpoint",
            topic_id="qg",
            claim_id="",
            reason="Review one exact knowledge candidate.",
            requested_by="pytest",
            options=["approve", "reject", "revise"],
            status="decided",
            decision="approve",
            rationale="The candidate boundary and source requirements were inspected.",
            decided_by="reviewer",
            decision_verified=verified,
            decision_verification="hmac_sha256_v1" if verified else "",
            decision_receipt_hash=f"sha256:{'a' * 64}" if verified else "",
            decision_receipt_nonce="knowledge-review-nonce" if verified else "",
            can_authorize_trust=verified,
            action="review_knowledge_candidate",
            subject_refs=[{"candidate_id": candidate.candidate_id, "candidate_hash": candidate_hash}],
            request_hash=candidate_hash,
            effect_policy="knowledge_review_only_no_claim_trust",
        ),
    )
    return PinnedRecordRef(result.record_ref, result.content_hash, result.revision)


def test_knowledge_review_requires_host_attested_hash_bound_checkpoint(tmp_path):
    from brain.v5.knowledge_review import record_knowledge_review_decision
    from brain.v5.workspace import create_topic, init_workspace

    ws = init_workspace(tmp_path)
    create_topic(ws, "qg", context_id="formal-theory", title="Quantum gravity")
    candidate = _candidate(_grounding(ws))
    checkpoint = _checkpoint(ws, candidate, verified=False)

    with pytest.raises(ValueError, match="host-attested"):
        record_knowledge_review_decision(
            ws,
            candidate,
            checkpoint_ref=checkpoint,
            decision="approve",
            actor=_actor(),
        )


def test_knowledge_review_rejects_candidate_changed_after_checkpoint(tmp_path):
    from brain.v5.knowledge_review import record_knowledge_review_decision
    from brain.v5.workspace import create_topic, init_workspace

    ws = init_workspace(tmp_path)
    create_topic(ws, "qg", context_id="formal-theory", title="Quantum gravity")
    candidate = _candidate(_grounding(ws))
    checkpoint = _checkpoint(ws, candidate)

    with pytest.raises(ValueError, match="candidate hash"):
        record_knowledge_review_decision(
            ws,
            replace(candidate, statement="Changed after human review."),
            checkpoint_ref=checkpoint,
            decision="approve",
            actor=_actor(),
        )


def test_knowledge_review_decision_is_append_only_and_trust_neutral(tmp_path):
    from brain.v5.knowledge_review import record_knowledge_review_decision
    from brain.v5.models import KnowledgeReviewDecisionRecord
    from brain.v5.record_family_registry import spec_for_family
    from brain.v5.record_repository import RecordRepository
    from brain.v5.workspace import create_topic, init_workspace

    ws = init_workspace(tmp_path)
    create_topic(ws, "qg", context_id="formal-theory", title="Quantum gravity")
    candidate = _candidate(_grounding(ws))
    checkpoint = _checkpoint(ws, candidate)

    result = record_knowledge_review_decision(
        ws,
        candidate,
        checkpoint_ref=checkpoint,
        decision="approve",
        actor=_actor(),
    )
    loaded = RecordRepository(ws, actor=_actor()).read(result.record_ref)

    assert isinstance(loaded.record, KnowledgeReviewDecisionRecord)
    assert loaded.record.candidate_id == candidate.candidate_id
    assert loaded.record.decision == "approve"
    assert loaded.record.rationale == "The candidate boundary and source requirements were inspected."
    assert loaded.record.reviewer == "reviewer"
    assert loaded.record.can_update_claim_trust is False
    assert spec_for_family("knowledge_review_decisions").lifecycle_policy == "append_only"
    assert spec_for_family("knowledge_review_decisions").trust_effect == "none"


@pytest.mark.parametrize(
    "content_kinds",
    [("procedural_workflow",), ("definition", "procedural_workflow")],
)
def test_knowledge_review_cannot_bypass_procedural_skill_review(tmp_path, content_kinds):
    from brain.v5.knowledge_candidates import KnowledgeCandidate
    from brain.v5.knowledge_review import record_knowledge_review_decision
    from brain.v5.workspace import create_topic, init_workspace

    ws = init_workspace(tmp_path)
    create_topic(ws, "qg", context_id="formal-theory", title="Quantum gravity")
    candidate = KnowledgeCandidate(
        candidate_id="workflow-candidate",
        content_kinds=content_kinds,
        statement="Run a reusable workflow.",
        topic_id="qg",
        procedural_steps=("run",),
        validation_refs=("validation_result:passed",),
        applicability_boundary="Only the validated fixture.",
    )
    checkpoint = _checkpoint(ws, candidate)

    with pytest.raises(ValueError, match="knowledge or insight lane"):
        record_knowledge_review_decision(
            ws,
            candidate,
            checkpoint_ref=checkpoint,
            decision="approve",
            actor=_actor(),
        )
