from __future__ import annotations

import pytest


def test_v2_physics_records_keep_v1_constructors_compatible():
    from brain.v5.models import ObjectRelationRecord, PhysicsObjectRecord

    legacy_object = PhysicsObjectRecord(
        object_id="algebra-a",
        topic_id="qg",
        object_type="operator_algebra",
        name="A",
        definition="A legacy inline definition.",
    )
    legacy_relation = ObjectRelationRecord(
        relation_id="rel-a-b",
        topic_id="qg",
        relation_type="included_in",
        subject_id="algebra-a",
        object_id="algebra-b",
        statement="A is included in B.",
    )

    assert legacy_object.canonical_name == ""
    assert legacy_object.knowledge_role == "identity"
    assert legacy_object.review_status == "legacy_unreviewed"
    assert legacy_relation.subject_ref == ""
    assert legacy_relation.object_ref == ""
    assert legacy_relation.claim_trust_transfer == "forbidden"


def test_v2_object_identity_and_assertion_provenance_are_separate():
    from brain.v5.models import PhysicsAssertionRecord, PhysicsObjectRecord

    obj = PhysicsObjectRecord(
        object_id="algebra-a",
        topic_id="qg",
        object_type="operator_algebra",
        name="A",
        definition="",
        scope_kind="topic",
        scope_ref="topic:qg",
        canonical_name="local algebra A",
        aliases=["A(O)"],
        review_status="reviewed",
    )
    assertion = PhysicsAssertionRecord(
        assertion_id="assertion-a-definition-haag",
        object_ref="physics_object:algebra-a",
        topic_id="qg",
        predicate="definition",
        value="The algebra generated by observables localized in O.",
        framework="algebraic QFT",
        regime="continuum local net",
        conventions=["isotony convention"],
        assumptions=["fixed spacetime background"],
        non_claims=["does not establish gravitational dressing"],
        source_asset_refs=["source_asset:haag-book"],
        source_location_refs=["reference_location:haag-local-algebra"],
        review_status="reviewed",
    )

    assert obj.definition == ""
    assert assertion.object_ref == "physics_object:algebra-a"
    assert assertion.source_location_refs == ["reference_location:haag-local-algebra"]
    assert assertion.can_update_claim_trust is False


def test_v2_relation_carries_scope_conditions_and_forbids_trust_transfer():
    from brain.v5.models import ObjectRelationRecord

    relation = ObjectRelationRecord(
        relation_id="rel-a-b",
        topic_id="qg",
        relation_type="included_in",
        subject_id="algebra-a",
        object_id="algebra-b",
        statement="A is included in B under isotony.",
        subject_ref="physics_object:algebra-a",
        object_ref="physics_object:algebra-b",
        direction="directed",
        conditions=["O_a subset O_b"],
        framework="algebraic QFT",
        regime="continuum local net",
        conventions=["isotony convention"],
        contradiction_refs=["object_relation:rel-a-b-counterexample"],
        review_status="reviewed",
        lifecycle_status="active",
    )

    assert relation.subject_id == "algebra-a"
    assert relation.subject_ref == "physics_object:algebra-a"
    assert relation.claim_trust_transfer == "forbidden"

    with pytest.raises(ValueError, match="trust transfer"):
        ObjectRelationRecord(
            relation_id="rel-unsafe",
            topic_id="qg",
            relation_type="implies",
            subject_id="algebra-a",
            object_id="claim-b",
            statement="Unsafe transfer.",
            claim_trust_transfer="allowed",
        )


def test_m3_record_families_are_registered_as_trust_neutral_v2():
    from brain.v5.record_family_registry import spec_for_family

    assertion = spec_for_family("physics_assertions")
    insight = spec_for_family("insights")

    assert assertion.schema_version == "v2"
    assert assertion.trust_effect == "none"
    assert insight.schema_version == "v2"
    assert insight.trust_effect == "none"
    assert insight.record_role == "orientation_only_record"


def test_v1_knowledge_migration_audit_is_read_only(tmp_path):
    from brain.v5.physics_knowledge_migration import audit_physics_knowledge_v1_compatibility
    from brain.v5.physics_objects import record_object_relation, record_physics_object
    from brain.v5.workspace import create_topic, init_workspace

    ws = init_workspace(tmp_path)
    create_topic(ws, "qg", context_id="formal-theory", title="Quantum gravity")
    obj = record_physics_object(
        ws,
        topic_id="qg",
        object_type="operator_algebra",
        name="A",
        definition="Legacy inline definition.",
        source_refs=["paper:haag"],
    )
    record_object_relation(
        ws,
        topic_id="qg",
        relation_type="included_in",
        subject_id=obj.object_id,
        object_id="algebra-b",
        statement="A is included in B.",
        source_refs=["paper:haag"],
    )
    before = {path: path.read_bytes() for path in ws.root.rglob("*.md")}

    report = audit_physics_knowledge_v1_compatibility(ws)
    after = {path: path.read_bytes() for path in ws.root.rglob("*.md")}

    assert report["object_count"] == 1
    assert report["relation_count"] == 1
    assert report["candidate_assertion_count"] == 1
    assert report["writes_records"] is False
    assert report["can_update_claim_trust"] is False
    assert before == after
