from __future__ import annotations

from dataclasses import replace

import pytest


def _actor():
    from brain.v5.record_envelope import RecordActor

    return RecordActor(actor_type="tool", actor_id="knowledge-promotion-test", host="pytest")


def _setup(tmp_path):
    from brain.v5.models import PhysicsObjectRecord, ReferenceLocationRecord, SourceAssetRecord
    from brain.v5.pinned_record_refs import pin_current_record
    from brain.v5.record_repository import RecordRepository
    from brain.v5.workspace import create_topic, init_workspace

    ws = init_workspace(tmp_path)
    create_topic(ws, "qg", context_id="formal-theory", title="Quantum gravity")
    repository = RecordRepository(ws, actor=_actor())
    repository.write(
        "source_assets",
        SourceAssetRecord(
            asset_id="haag-book",
            topic_id="qg",
            asset_type="book",
            uri="file:///sources/haag.pdf",
            title="Local Quantum Physics",
            content_hash="a" * 64,
            hash_algorithm="sha256",
        ),
    )
    repository.write(
        "reference_locations",
        ReferenceLocationRecord(
            location_id="haag-local-algebra",
            topic_id="qg",
            connector_id="local-source",
            location_type="page_anchor",
            uri="file:///sources/haag.pdf#page=101",
            label="Local algebra definition",
            source_ref="source_asset:haag-book",
        ),
    )
    repository.write(
        "physics_objects",
        PhysicsObjectRecord(
            object_id="local-algebra",
            topic_id="qg",
            object_type="operator_algebra",
            name="Local algebra",
            definition="Stable identity for the local observable algebra.",
        ),
    )
    pins = (
        pin_current_record(ws, "source_asset:haag-book"),
        pin_current_record(ws, "reference_location:haag-local-algebra"),
    )
    return ws, pins


def _candidate(pins):
    from brain.v5.knowledge_candidates import KnowledgeCandidate

    return KnowledgeCandidate(
        candidate_id="local-algebra-definition",
        content_kinds=("definition",),
        statement="A(O) is generated by observables localized in O.",
        topic_id="qg",
        subject_ref="physics_object:local-algebra",
        grounding_pins=tuple(pins),
        framework="algebraic QFT",
        regime="continuum local net",
        conventions=("Haag-Kastler net",),
    )


def _review_checkpoint(
    ws,
    candidate,
    *,
    decision="approve",
    checkpoint_id="",
):
    from brain.v5.knowledge_review import knowledge_candidate_hash
    from brain.v5.models import HumanCheckpointRecord
    from brain.v5.pinned_record_refs import PinnedRecordRef
    from brain.v5.record_repository import RecordRepository

    candidate_hash = knowledge_candidate_hash(candidate)
    checkpoint_id = checkpoint_id or f"knowledge-promotion-{decision}"
    checkpoint = RecordRepository(ws, actor=_actor()).write(
        "checkpoints",
        HumanCheckpointRecord(
            checkpoint_id=checkpoint_id,
            topic_id="qg",
            claim_id="",
            reason="Review exact promotion candidate.",
            requested_by="pytest",
            options=["approve", "reject", "revise"],
            status="decided",
            decision=decision,
            rationale=f"Human decision: {decision}.",
            decided_by="reviewer",
            decision_verified=True,
            decision_verification="hmac_sha256_v1",
            decision_receipt_hash=f"sha256:{'b' * 64}",
            decision_receipt_nonce=f"knowledge-promotion-{decision}-nonce",
            can_authorize_trust=True,
            action="review_knowledge_candidate",
            subject_refs=[{"candidate_id": candidate.candidate_id, "candidate_hash": candidate_hash}],
            request_hash=candidate_hash,
            effect_policy="knowledge_review_only_no_claim_trust",
        ),
    )
    checkpoint_pin = PinnedRecordRef(
        checkpoint.record_ref,
        checkpoint.content_hash,
        checkpoint.revision,
    )
    return checkpoint_pin


def _review(ws, candidate, *, decision="approve"):
    from brain.v5.knowledge_review import record_knowledge_review_decision
    from brain.v5.pinned_record_refs import PinnedRecordRef

    result = record_knowledge_review_decision(
        ws,
        candidate,
        checkpoint_ref=_review_checkpoint(ws, candidate, decision=decision),
        decision=decision,
        actor=_actor(),
    )
    return PinnedRecordRef(result.record_ref, result.content_hash, result.revision)


def test_approved_grounded_candidate_promotes_to_reviewed_assertion(tmp_path):
    from brain.v5.knowledge_promotion import promote_knowledge_candidate
    from brain.v5.models import PhysicsAssertionRecord
    from brain.v5.record_repository import RecordRepository

    ws, pins = _setup(tmp_path)
    candidate = _candidate(pins)
    decision_pin = _review(ws, candidate)

    result = promote_knowledge_candidate(
        ws,
        candidate,
        decision_ref=decision_pin,
        actor=_actor(),
    )
    repository = RecordRepository(ws, actor=_actor())
    assertion = repository.read(result.record_ref).record

    assert isinstance(assertion, PhysicsAssertionRecord)
    assert assertion.object_ref == "physics_object:local-algebra"
    assert assertion.value == candidate.statement
    assert assertion.review_status == "reviewed"
    assert assertion.source_asset_refs == ["source_asset:haag-book"]
    assert assertion.source_location_refs == ["reference_location:haag-local-algebra"]
    assert assertion.review_decision_ref == vars(decision_pin)
    assert assertion.can_update_claim_trust is False
    assert repository.list("evidence").records == ()
    assert repository.list("trust_updates").records == ()


def test_approved_insight_promotes_only_to_non_evidence_insight(tmp_path):
    from brain.v5.knowledge_candidates import KnowledgeCandidate
    from brain.v5.knowledge_promotion import promote_knowledge_candidate
    from brain.v5.models import InsightRecord
    from brain.v5.record_repository import RecordRepository

    ws, _pins = _setup(tmp_path)
    candidate = KnowledgeCandidate(
        candidate_id="island-analogy",
        content_kinds=("analogy",),
        statement="The inclusion pattern may be analogous to an island transition.",
        topic_id="qg",
        framework="algebraic QFT",
        regime="semiclassical comparison",
    )
    decision_pin = _review(ws, candidate)

    result = promote_knowledge_candidate(
        ws,
        candidate,
        decision_ref=decision_pin,
        actor=_actor(),
    )
    repository = RecordRepository(ws, actor=_actor())
    insight = repository.read(result.record_ref).record

    assert isinstance(insight, InsightRecord)
    assert insight.insight_kind == "analogy"
    assert insight.review_status == "reviewed"
    assert insight.review_decision_ref == vars(decision_pin)
    assert insight.evidence_role == "forbidden"
    assert insight.can_update_claim_trust is False
    assert repository.list("evidence").records == ()
    assert repository.list("trust_updates").records == ()


def test_promotion_rejects_candidate_changed_after_review(tmp_path):
    from brain.v5.knowledge_promotion import promote_knowledge_candidate

    ws, pins = _setup(tmp_path)
    candidate = _candidate(pins)
    decision_pin = _review(ws, candidate)

    with pytest.raises(ValueError, match="candidate hash"):
        promote_knowledge_candidate(
            ws,
            replace(candidate, statement="Changed after review."),
            decision_ref=decision_pin,
            actor=_actor(),
        )


def test_rejected_candidate_cannot_promote_or_write_any_lane(tmp_path):
    from brain.v5.knowledge_promotion import promote_knowledge_candidate
    from brain.v5.record_repository import RecordRepository

    ws, pins = _setup(tmp_path)
    candidate = _candidate(pins)
    decision_pin = _review(ws, candidate, decision="reject")

    with pytest.raises(ValueError, match="approved"):
        promote_knowledge_candidate(
            ws,
            candidate,
            decision_ref=decision_pin,
            actor=_actor(),
        )

    repository = RecordRepository(ws, actor=_actor())
    assert repository.list("physics_assertions").records == ()
    assert repository.list("insights").records == ()
    assert repository.list("evidence").records == ()
    assert repository.list("trust_updates").records == ()


def test_superseded_approval_cannot_promote(tmp_path):
    from brain.v5.knowledge_promotion import promote_knowledge_candidate
    from brain.v5.knowledge_review import supersede_knowledge_review_decision

    ws, pins = _setup(tmp_path)
    candidate = _candidate(pins)
    approval_pin = _review(ws, candidate)
    revised = replace(candidate, statement="A revised candidate requiring another review.")
    replacement_checkpoint = _review_checkpoint(
        ws,
        revised,
        decision="revise",
        checkpoint_id="knowledge-promotion-revise",
    )
    supersede_knowledge_review_decision(
        ws,
        revised,
        prior_decision_ref=approval_pin,
        checkpoint_ref=replacement_checkpoint,
        decision="revise",
        actor=_actor(),
    )

    with pytest.raises(ValueError, match="superseded"):
        promote_knowledge_candidate(
            ws,
            candidate,
            decision_ref=approval_pin,
            actor=_actor(),
        )


def test_promotion_fails_closed_on_branched_review_history(tmp_path):
    from brain.v5.knowledge_promotion import promote_knowledge_candidate
    from brain.v5.pinned_record_refs import PinnedRecordRef
    from brain.v5.record_repository import RecordRepository

    ws, pins = _setup(tmp_path)
    candidate = _candidate(pins)
    approval_pin = _review(ws, candidate)
    repository = RecordRepository(ws, actor=_actor())
    approval = repository.read(approval_pin.record_ref).record
    branch_pins = []
    for suffix in ("a", "b"):
        branch = replace(
            approval,
            decision_id=f"branched-review-{suffix}",
            supersedes_decision_ref=vars(approval_pin),
        )
        result = repository.write("knowledge_review_decisions", branch)
        branch_pins.append(
            PinnedRecordRef(result.record_ref, result.content_hash, result.revision)
        )

    with pytest.raises(ValueError, match="multiple active branches"):
        promote_knowledge_candidate(
            ws,
            candidate,
            decision_ref=branch_pins[0],
            actor=_actor(),
        )
