"""Shared validation entrypoints for public AITP v5 surfaces."""

from __future__ import annotations

from typing import Any, Callable

_PUBLIC_SURFACE_NAMES = (
    "adapter_packet",
    "adapter_protocol_registry",
    "artifact_record",
    "bounded_numerical_evidence_bundle",
    "claim_status_record",
    "claim_relation_map",
    "claim_trust_audit",
    "claude_code_hook_installation",
    "claude_code_hook_settings",
    "codex_hook_bridge",
    "codex_hook_installation",
    "code_state_record",
    "curated_rag_chunk",
    "curated_rag_corpus",
    "curated_rag_ingest_result",
    "curated_rag_promotion_draft",
    "curated_rag_search_result",
    "evidence_record",
    "execution_brief",
    "exploratory_record",
    "failure_mode_audit",
    "failure_mode_review_packet",
    "failure_mode_review_result_record",
    "final_engineering_readiness_audit",
    "final_output_profile",
    "human_checkpoint_record",
    "hook_trace_event_record",
    "interaction_recording_preview",
    "interaction_recording_worklist",
    "workspace_interaction_preview_bundle",
    "literature_comparison_draft",
    "literature_intake_record_result",
    "literature_intake_suggestion",
    "literature_source_review_handoff",
    "kimi_code_hook_config",
    "kimi_code_hook_installation",
    "knowledge_connector_catalog",
    "lane_exemplar_manifest",
    "lane_exemplar_record",
    "l2_obsidian_view_bundle",
    "l2_memory_audit",
    "lifecycle_event_record",
    "legacy_executable_evidence_packet",
    "legacy_human_checkpoint_obsidian_view_bundle",
    "legacy_human_checkpoint_packet",
    "legacy_topic_question_backfill_packet",
    "legacy_l2_graph_manifest",
    "legacy_l2_obsidian_view_bundle",
    "canonical_legacy_l2_seed_audit",
    "canonical_legacy_l2_seed_review_worklist",
    "legacy_l2_seed_group_review_result_record",
    "legacy_l2_typed_migration_packet",
    "legacy_migration_coverage_audit",
    "legacy_migration_result",
    "legacy_runtime_log_marker_audit",
    "legacy_source_metadata_repair_packet",
    "legacy_source_reconstruction_apply",
    "legacy_source_reconstruction_manifest",
    "legacy_source_reconstruction_obsidian_view_bundle",
    "legacy_source_reconstruction_plan",
    "legacy_source_reconstruction_review_packet",
    "legacy_semantic_needs_revision_basis_obsidian_view_bundle",
    "legacy_semantic_needs_revision_basis_packet",
    "legacy_semantic_needs_revision_basis_queue",
    "legacy_semantic_review_manifest",
    "legacy_semantic_review_obsidian_view_bundle",
    "legacy_semantic_review_packet",
    "legacy_semantic_review_worklist",
    "legacy_semantic_repair_apply",
    "legacy_semantic_repair_manifest",
    "legacy_semantic_repair_plan",
    "legacy_semantic_review_result_record",
    "legacy_semantic_review_queue",
    "memory_entry_record",
    "object_relation_record",
    "operator_checkpoint_record",
    "opencode_hook_installation",
    "opencode_plugin_bridge",
    "host_agnostic_moment_policy",
    "physics_object_record",
    "pre_tool_policy_decision",
    "process_graph_slice",
    "promotion_packet_record",
    "proof_obligation_record",
    "qsgw_cockpit_bundle",
    "record_gate_coverage_audit",
    "recording_candidate_classification",
    "recording_effect_verification",
    "recording_navigation_state",
    "recording_slot_expansion",
    "record_ref_lookup",
    "reference_location_record",
    "research_route_record",
    "research_event_classification",
    "research_cockpit_bundle",
    "research_intent_packet",
    "research_run_event_record",
    "research_run_record",
    "run_iteration_record",
    "runtime_hook_installation_audit",
    "runtime_host_lifecycle_audit",
    "runtime_host_production_loop_audit",
    "runtime_host_readiness_audit",
    "runtime_bridge_target_manifest",
    "runtime_mcp_bridge_acceptance",
    "runtime_payload_profiles",
    "runtime_hook_installation_paths",
    "runtime_hook_smoke_coverage",
    "sensemaking_report_record",
    "session_summary_bundle",
    "source_reconstruction_audit",
    "source_asset_record",
    "source_stack_coverage_manifest",
    "source_reconstruction_manifest",
    "source_reconstruction_obsidian_view_bundle",
    "source_reconstruction_review_manifest",
    "source_reconstruction_review_packet",
    "source_reconstruction_review_result_record",
    "steering_decision_record",
    "strategy_memory_record",
    "summary_orientation",
    "tool_executor_catalog",
    "topic_status_bundle",
    "tool_recipe_record",
    "tool_run_record",
    "trust_update_record",
    "trust_update_apply",
    "trust_update_preflight",
    "validation_contract_record",
    "validation_result_record",
    "vnext_readiness_manifest",
    "workspace_summary_bundle",
    "workspace_replay_packet",
    "workspace_refresh_bundle",
    "workspace_file_migration_ledger",
    "workspace_file_migration_ledger_progress",
    "workspace_migration_health",
    "workspace_old_store_import_result",
    "workspace_recovery_binding_repair",
    "workspace_recovery_audit",
    "workspace_recovery_audit_progress",
    "workspace_recording_audit",
    "goal_continuation_packet",
    "goal_continuation_list",
)
_PUBLIC_SURFACE_VALIDATOR_REF = "brain.v5.public_surfaces.require_valid_public_surface"
_PUBLIC_SURFACE_PURPOSES = {
    "adapter_packet": "runtime adapter packet carrying brief, summary orientation, and trust protocol metadata",
    "adapter_protocol_registry": "auditable registry metadata for adapter protocol fields and validator surfaces",
    "artifact_record": "contracted artifact pointer preserving provenance, hashes, and by-reference result files",
    "bounded_numerical_evidence_bundle": "guarded composition of artifact, tool-run, evidence, and claim-status records for finite/run-bounded numerical results without trust promotion",
    "claim_status_record": "contracted append-only claim maturity/status observation that never mutates claim trust",
    "claim_relation_map": "derived read-only relation map that explains support, limits, non-testing failures, blockers, and conclusion boundaries for recovery without updating claim trust",
    "claim_trust_audit": "read-only typed-record audit of whether a claim confidence state has evidence, validation, memory, and code provenance support",
    "claude_code_hook_installation": "contracted safe merge of AITP hooks into Claude Code settings without treating settings as truth",
    "claude_code_hook_settings": "contracted Claude Code hook settings generated from runtime hook installation metadata",
    "codex_hook_bridge": "contracted Codex hook bridge generated from runtime hook installation metadata",
    "codex_hook_installation": "contracted Codex stdin-runner hook installation fixture generated from runtime metadata",
    "code_state_record": "contracted code-state provenance record for code-dependent physics results",
    "curated_rag_chunk": "read-only curated RAG chunk lookup exposing canonical chunk/document identity, hash, anchor, and source metadata without evidence, validation, final-gate, or claim-trust authority",
    "curated_rag_corpus": "read-only curated background RAG corpus catalog for heuristic context without evidence, validation, or claim-trust authority",
    "curated_rag_ingest_result": "contracted file-backed curated RAG manifest/index write result for heuristic background corpus updates without evidence, validation, final-gate, or claim-trust authority",
    "curated_rag_promotion_draft": "read-only curated RAG escalation draft that proposes normal source, evidence, validation, and trust-preflight records without creating claim support or trust authority",
    "curated_rag_search_result": "read-only curated background RAG retrieval result marked heuristic_context and unable to satisfy evidence, validation, final-gate, or trust boundaries",
    "evidence_record": "contracted evidence write result linked to a claim and required outputs",
    "execution_brief": "typed kernel brief for current focus, risk, evidence coverage, and next actions",
    "exploratory_record": "contracted orientation-only record for source assets, question decomposition, relation-path brainstorming, backtrace steps, and steering checkpoints before claim trust changes",
    "failure_mode_audit": "read-only typed-record audit of claim, validation, and promotion failure-mode coverage",
    "failure_mode_review_packet": "read-only physics adequacy review questions for recorded failure modes",
    "failure_mode_review_result_record": "contracted typed record preserving the evidence/tool/literature basis behind an approved failure-mode review",
    "final_engineering_readiness_audit": "orientation-only final-gap audit separating AITP v5 kernel capability from remaining host and legacy semantic-review backlog",
    "final_output_profile": "contracted topic-local output shape profile for stable final/handoff reports without claim-trust authority",
    "human_checkpoint_record": "contracted human checkpoint requiring explicit options and a decision from the declared option set",
    "hook_trace_event_record": "contracted persisted hook trace-event record that cannot update claim trust",
    "interaction_recording_preview": "read-only preview of natural conversation recording boundaries, lightweight mode, and heavier triggers",
    "interaction_recording_worklist": "orientation-only workspace worklist translating natural conversation recording boundaries into conservative kernel entrypoint templates",
    "workspace_interaction_preview_bundle": "orientation-only host startup bundle summarizing per-session natural conversation recording boundaries without updating kernel state",
    "literature_comparison_draft": "read-only literature comparison draft packet that scaffolds source-set dimensions, agreements, disagreements, missing evidence, and open directions without creating comparison, evidence, validation, final-gate, or trust authority",
    "literature_intake_record_result": "guarded literature intake write result that records only an orientation reference location and returns non-trust-changing evidence/sensemaking candidates",
    "literature_intake_suggestion": "read-only literature intake suggestion that proposes reference, sensemaking, and scoped evidence templates without treating summaries as evidence",
    "literature_source_review_handoff": "read-only handoff packet composing literature intake, record-ref lookup, source-stack coverage, and source reconstruction review without source-support, validation, write, final-gate, or trust authority",
    "kimi_code_hook_config": "contracted Kimi Code TOML hook config generated from runtime hook installation metadata",
    "kimi_code_hook_installation": "contracted safe merge of AITP hooks into Kimi Code TOML config without treating config as truth",
    "knowledge_connector_catalog": "contracted catalog of knowledge connectors for notes, literature, and learning memory",
    "lane_exemplar_manifest": "orientation-only vNext Phase 5 lane exemplar closure manifest that cannot update claim trust",
    "lane_exemplar_record": "contracted vNext lane-specific exemplar record for workflow closure, not evidence or promotion",
    "l2_obsidian_view_bundle": "orientation-only Obsidian Markdown view over typed L2 memory entries",
    "l2_memory_audit": "read-only typed-record audit of L2 memory provenance for one claim",
    "lifecycle_event_record": "append-only provenance log for record rehome/supersede lifecycle changes",
    "legacy_executable_evidence_packet": "read-only packet grouping validation and tool-run evidence actions that block legacy semantic review pass without changing claim trust",
    "legacy_human_checkpoint_obsidian_view_bundle": "orientation-only Obsidian Markdown worklist over open and pending legacy semantic-review human checkpoints",
    "legacy_human_checkpoint_packet": "read-only packet grouping open and pending human checkpoint decisions required by legacy semantic review without changing claim trust",
    "legacy_topic_question_backfill_packet": "read-only packet for ambiguous legacy topic-question claim-statement backfill blockers that require human confirmation before any repair",
    "legacy_l2_graph_manifest": "read-only manifest for planning legacy global L2 graph/index migration into typed L2 memory and Obsidian views",
    "legacy_l2_obsidian_view_bundle": "orientation-only Obsidian Markdown view over legacy global L2 entries and graph counts before typed migration",
    "canonical_legacy_l2_seed_audit": "read-only audit of canonical memory entries imported as legacy L2 seeds, keeping them orientation-only until reviewed or quarantined",
    "canonical_legacy_l2_seed_review_worklist": "read-only grouped worklist for reviewing canonical legacy L2 seed memory by topic, target scope, source claim, and role before archive or evidence-backed promotion",
    "legacy_l2_seed_group_review_result_record": "contracted typed review result for one canonical legacy L2 seed group; records archive/reassign/promotion-candidate decisions without claim-trust authority",
    "legacy_l2_typed_migration_packet": "orientation-only grouped review packet for converting legacy L2 graph work items into typed records without trusting archive contents",
    "legacy_migration_coverage_audit": "read-only audit of legacy migration file accounting, archive references, and per-topic coverage without claiming semantic proof",
    "legacy_migration_result": "contracted explicit migration result from legacy topic files into v5 typed records",
    "legacy_runtime_log_marker_audit": "read-only marker audit over explicitly provided raw runtime logs, separating raw evidence from orientation summaries without changing claim trust",
    "legacy_source_metadata_repair_packet": "read-only packet grouping DOI, citation, and bibliography metadata repair work from legacy semantic-review blockers without changing claim trust",
    "legacy_source_reconstruction_apply": "guarded evidence backfill for reconstruction-path coverage derived from typed legacy semantic reviews without changing claim trust",
    "legacy_source_reconstruction_manifest": "orientation-only batch triage manifest for legacy source reconstruction repair and review actions without changing claim trust",
    "legacy_source_reconstruction_obsidian_view_bundle": "orientation-only Obsidian Markdown worklist over legacy source reconstruction repair and review backlog",
    "legacy_source_reconstruction_plan": "read-only plan for reconstruction-path evidence backfills derived from typed legacy semantic reviews",
    "legacy_source_reconstruction_review_packet": "read-only legacy-aware source reconstruction review packet that maps migrated refs onto typed reconstruction components without mutating trust",
    "legacy_semantic_needs_revision_basis_obsidian_view_bundle": "orientation-only Obsidian Markdown worklist over inconclusive legacy semantic reviews that need typed needs-revision review basis",
    "legacy_semantic_needs_revision_basis_packet": "orientation-only per-topic packet collecting reviewed refs, checkpoint refs, likely repair basis, and a typed needs-revision result command without changing claim trust",
    "legacy_semantic_needs_revision_basis_queue": "read-only queue for converting inconclusive legacy semantic reviews into specific needs-revision review basis without changing claim trust",
    "legacy_semantic_review_manifest": "orientation-only batch manifest listing per-topic semantic review packets, statuses, and result-record commands",
    "legacy_semantic_review_obsidian_view_bundle": "orientation-only Obsidian Markdown worklist over legacy semantic-review backlog items, blockers, and result commands",
    "legacy_semantic_review_packet": "orientation-only per-topic packet collecting migrated legacy refs, typed records, and checklist for actual semantic review",
    "legacy_semantic_review_worklist": "orientation-only prioritized worklist for remaining legacy semantic-review backlog without claiming semantic losslessness",
    "legacy_semantic_repair_apply": "guarded content repair application derived from typed legacy semantic review results without changing claim trust",
    "legacy_semantic_repair_manifest": "orientation-only batch triage manifest for legacy semantic repair status, including external-evidence-required validation follow-up, without changing claim trust",
    "legacy_semantic_repair_plan": "read-only repair plan derived from typed legacy semantic review results without applying claim trust or kernel-state mutations",
    "legacy_semantic_review_result_record": "contracted per-topic legacy migration semantic review result with explicit review basis and no claim-trust mutation authority",
    "legacy_semantic_review_queue": "orientation-only per-topic semantic review queue for completed legacy migrations, linking accounting coverage to typed source reconstruction gaps without claiming semantic proof",
    "memory_entry_record": "contracted L2 memory entry created only from evidence-backed promotion packets with human approval",
    "object_relation_record": "contracted object-relation record linking physics objects with typed relations, failure modes, and assumptions",
    "operator_checkpoint_record": "contracted topic-local operator question that survives restarts and cannot update claim trust",
    "opencode_hook_installation": "contracted OpenCode stdin-runner hook installation fixture generated from runtime metadata",
    "opencode_plugin_bridge": "contracted OpenCode plugin bridge generated from runtime hook installation metadata",
    "host_agnostic_moment_policy": "read-only policy over typed process-graph records for when to record, brainstorm/backtrace, or stop at a trust boundary",
    "physics_object_record": "contracted physics-object record for theoretical objects, systems, operators, sectors, and definitions",
    "pre_tool_policy_decision": "contracted pre-tool policy decision derived from typed kernel records, not summaries",
    "process_graph_slice": "read-only host-agnostic process graph slice over typed records; orientation-only and unable to mutate kernel state or claim trust",
    "promotion_packet_record": "contracted promotion packet requiring explicit evidence refs, known failure modes, and scope before L2 memory promotion",
    "proof_obligation_record": "contracted proof/theorem obligation record for open gaps, finite audits, and theorem-candidate status without trust mutation",
    "qsgw_cockpit_bundle": "orientation-only QSGW/LibRPA research cockpit bundle with final/diagnostic lane manifest, plot guard, and dashboard dry-run that cannot update claim trust",
    "record_gate_coverage_audit": "contracted audit that every runtime record protocol has a conscious runtime gate decision",
    "recording_candidate_classification": "read-only progressive recording trigger classifier that decides ignore, defer, navigate, or checkpoint before any AITP write",
    "recording_navigation_state": "read-only lightweight first-level navigator over session, claim, slot counts, relation boundary, and recording slots; it does not replace execution_brief or process_graph_slice",
    "recording_slot_expansion": "read-only slot expansion that names the existing typed write/preflight tool, required fields, graph edges, and verification step",
    "recording_effect_verification": "read-only post-write verification surface over typed refs and process-graph deltas without updating claim trust",
    "record_ref_lookup": "read-only typed-store existence lookup for canonical record refs without source support, validation, evidence creation, or claim-trust mutation",
    "reference_location_record": "contracted orientation-only pointer to an external paper, note, or knowledge item",
    "research_route_record": "contracted orientation-only route, branch, failed-attempt, or pivot record for nonlinear research process state",
    "research_event_classification": "orientation-only event classifier that recommends source, evidence, failed-route, open-gap, claim-update, or prior-art handling without writing trust",
    "research_cockpit_bundle": "orientation-only workspace research cockpit that aggregates topic status, learning gaps, reading queue, and operator decisions without becoming a truth source",
    "research_intent_packet": "contracted vNext idea gate packet for vague or materially redefined research topics",
    "research_run_event_record": "contracted process event for a research run, preserving operator/action/status provenance without evidence, validation, final-gate, or claim-trust authority",
    "research_run_record": "contracted canonical research run ledger for objective, question, operator trail, AITP refs, action refs, and terminal answer state without claim-trust authority",
    "run_iteration_record": "contracted run-local L3/L4/L3 iteration continuity record with Markdown-first review and no claim-trust authority",
    "runtime_hook_installation_audit": "read-only audit of installed runtime hook files; runtime metadata only, never kernel truth",
    "runtime_host_lifecycle_audit": "dynamic read-only probe that runs a host command and checks stdout/stderr plus hook trace deltas for lifecycle-event evidence",
    "runtime_host_production_loop_audit": "dynamic read-only batch audit over priority runtime host production loops without updating kernel truth",
    "runtime_host_readiness_audit": "dynamic read-only audit that launches the local host command and checks installed hook files without updating kernel truth",
    "runtime_bridge_target_manifest": "MCP-first host bridge target manifest derived from canonical runtime entrypoints with CLI fallback templates and no claim-trust mutation authority",
    "runtime_mcp_bridge_acceptance": "read-only acceptance check comparing live MCP bridge exposure against the canonical runtime bridge target manifest",
    "runtime_payload_profiles": "host-event to typed AITP write payload profiles for provenance capture without validation or claim-trust authority",
    "runtime_hook_installation_paths": "read-only discovery of workspace-local hook install targets for Codex, Claude Code, Kimi Code, and OpenCode",
    "runtime_hook_smoke_coverage": "read-only report of which generated runtime hook paths have test-backed smoke coverage",
    "sensemaking_report_record": "contracted local sense-making report — orientation-only, never a validation gate",
    "session_summary_bundle": "orientation-only summary files regenerated from typed kernel records",
    "source_reconstruction_audit": "read-only typed-record audit of whether a claim has definition, scope, source, dependency, reconstruction, and failure-condition coverage",
    "source_asset_record": "contracted orientation-only canonical identity for raw papers, lectures, notes, code snapshots, datasets, generated artifacts, and other source assets",
    "source_stack_coverage_manifest": "read-only manifest combining evidence required-output coverage, source reconstruction, and source review status across active claims",
    "source_reconstruction_manifest": "read-only backlog manifest batching source reconstruction gaps and next actions across active claims",
    "source_reconstruction_obsidian_view_bundle": "orientation-only Obsidian Markdown worklist over source reconstruction review gaps from typed records",
    "source_reconstruction_review_manifest": "orientation-only manifest of typed source reconstruction review results and remaining component-review actions",
    "source_reconstruction_review_packet": "read-only packet guiding human typed-record backfill for source reconstruction gaps without mutating kernel state or claim trust",
    "source_reconstruction_review_result_record": "contracted typed result preserving the basis for source reconstruction component review without changing claim trust",
    "steering_decision_record": "contracted durable steering redirect record that cannot update claim trust",
    "strategy_memory_record": "contracted run-local workflow lesson for future topic continuation; non-promotional and not claim evidence",
    "summary_orientation": "read-only summary view with explicit truth-source protections",
    "tool_executor_catalog": "contracted catalog of safe built-in tool executors and input schemas",
    "topic_status_bundle": "orientation-only topic status files explaining current route, blockers, last evidence return, and operator needs",
    "tool_recipe_record": "contracted reusable tool recipe record with inputs, outputs, and invariants",
    "tool_run_record": "contracted tool-run provenance record linked to claims, code states, and artifacts",
    "trust_update_record": "contracted durable history record for a trust-update apply attempt",
    "trust_update_apply": "contracted result of a trust-changing mutation after preflight",
    "trust_update_preflight": "contracted preflight gate for trust-changing actions",
    "validation_contract_record": "contracted validation contract requiring explicit checks, failure modes, and evidence outputs before a claim can be validated",
    "validation_result_record": "contracted validation result linking a tool run to a validation contract and checked outputs",
    "vnext_readiness_manifest": "orientation-only vNext readiness manifest separating implemented control-plane surfaces from lane exemplar and content backlog",
    "workspace_summary_bundle": "orientation-only workspace summary regenerated from typed sessions, active claims, memory entries, and validation links",
    "workspace_replay_packet": "orientation-only multi-session replay packet listing resume attention, source reconstruction gaps, evidence gaps, and next actions from typed records",
    "workspace_refresh_bundle": "orientation-only host refresh bundle; full mode refreshes replay/source/L2 views, while startup_lightweight mode refreshes current-session orientation only",
    "workspace_file_migration_ledger": "file-level import/archive/review ledger for retiring noncanonical AITP stores without mutating claim trust",
    "workspace_file_migration_ledger_progress": "compact file-level migration ledger progress surface for agent startup and migration discipline",
    "workspace_migration_health": "compact recovery boundary over file-migration progress and canonical legacy L2 seed quarantine status without claim-trust authority",
    "workspace_old_store_import_result": "controlled root/nested old-store typed-file import result with conflict checks and no claim-trust authority",
    "workspace_recovery_binding_repair": "conservative active-claim session binding repair for restart recovery; auto-applies only when a topic has exactly one canonical claim",
    "workspace_recovery_audit": "read-only per-topic audit of restart recovery readiness, active-claim binding, relation-map boundaries, and migration review blockers",
    "workspace_recovery_audit_progress": "compact per-topic restart recovery progress surface for agent startup and migration discipline",
    "workspace_recording_audit": "read-only workspace-level recording navigation audit that tells agents which topics can enter progressive slot expansion and which require human or recovery review first",
    "goal_continuation_packet": "orientation-only local audit packet for cross-session goal continuation; records objective, commits, changed files, tests, smoke, readiness, next actions, and blocking backlog without changing kernel state",
    "goal_continuation_list": "orientation-only index of local goal continuation packets for cross-session audit discovery without changing kernel state",
}


def public_surface_names() -> tuple[str, ...]:
    """Return the names of public payload surfaces with contract gates."""

    return _PUBLIC_SURFACE_NAMES


def public_surface_validator_ref() -> str:
    """Return the stable import path for validating public payload surfaces."""

    return _PUBLIC_SURFACE_VALIDATOR_REF


def describe_public_surfaces() -> dict[str, Any]:
    """Return an auditable description of public surface contract coverage."""

    return {
        "kind": "public_surface_contracts",
        "validator": public_surface_validator_ref(),
        "surface_names": list(public_surface_names()),
        "surfaces": [
            {
                "name": name,
                "validator": public_surface_validator_ref(),
                "purpose": _PUBLIC_SURFACE_PURPOSES[name],
            }
            for name in public_surface_names()
        ],
        "truth_source": "contract_registry",
        "summary_inputs_trusted": False,
    }


def require_valid_public_surface(surface_name: str, payload: dict[str, Any]) -> dict[str, Any]:
    """Validate a public payload by stable surface name."""

    validator = _validators().get(surface_name)
    if validator is None:
        raise ValueError(f"unknown public surface: {surface_name}")
    return validator(payload)


def _validators() -> dict[str, Callable[[dict[str, Any]], dict[str, Any]]]:
    from brain.v5.contracts import (
        require_valid_adapter_packet,
        require_valid_adapter_protocol_registry,
        require_valid_artifact_record,
        require_valid_claim_status_record,
        require_valid_claim_relation_map,
        require_valid_claim_trust_audit,
        require_valid_codex_hook_bridge,
        require_valid_code_state_record,
        require_valid_evidence_record,
        require_valid_lifecycle_event_record,
        require_valid_execution_brief,
        require_valid_exploratory_record,
        require_valid_failure_mode_audit,
        require_valid_failure_mode_review_packet,
        require_valid_failure_mode_review_result_record,
        require_valid_final_engineering_readiness_audit,
        require_valid_human_checkpoint_record,
        require_valid_knowledge_connector_catalog,
        require_valid_l2_memory_audit,
        require_valid_memory_entry_record,
        require_valid_object_relation_record,
        require_valid_physics_object_record,
        require_valid_process_graph_slice,
        require_valid_promotion_packet_record,
        require_valid_proof_obligation_record,
        require_valid_record_gate_coverage_audit,
        require_valid_record_ref_lookup,
        require_valid_reference_location_record,
        require_valid_research_route_record,
        require_valid_research_run_event_record,
        require_valid_research_run_record,
        require_valid_runtime_bridge_target_manifest,
        require_valid_runtime_mcp_bridge_acceptance,
        require_valid_runtime_hook_installation_audit,
        require_valid_runtime_hook_installation_paths,
        require_valid_runtime_hook_smoke_coverage,
        require_valid_sensemaking_report_record,
        require_valid_source_asset_record,
        require_valid_session_summary_bundle,
        require_valid_source_reconstruction_audit,
        require_valid_summary_orientation,
        require_valid_tool_executor_catalog,
        require_valid_tool_recipe_record,
        require_valid_tool_run_record,
        require_valid_trust_update_record,
        require_valid_trust_update_apply,
        require_valid_trust_update_preflight,
        require_valid_validation_contract_record,
        require_valid_validation_result_record,
        require_valid_workspace_summary_bundle,
        require_valid_workspace_replay_packet,
    )
    from brain.v5.research_state_contracts import (
        require_valid_bounded_numerical_evidence_bundle,
        require_valid_research_event_classification,
    )
    from brain.v5.research_intent_contracts import (
        require_valid_research_intent_packet,
        require_valid_steering_decision_record,
    )
    from brain.v5.run_iteration_contracts import require_valid_run_iteration_record
    from brain.v5.output_stability_contracts import require_valid_final_output_profile
    from brain.v5.operator_checkpoint_contracts import require_valid_operator_checkpoint_record
    from brain.v5.strategy_memory_contracts import require_valid_strategy_memory_record
    from brain.v5.topic_status_contracts import require_valid_topic_status_bundle
    from brain.v5.legacy_contracts import require_valid_legacy_migration_result
    from brain.v5.legacy_executable_evidence_contracts import require_valid_legacy_executable_evidence_packet
    from brain.v5.legacy_human_checkpoint_obsidian_contracts import require_valid_legacy_human_checkpoint_obsidian_view_bundle
    from brain.v5.legacy_human_checkpoint_packet_contracts import require_valid_legacy_human_checkpoint_packet
    from brain.v5.legacy_topic_question_backfill_contracts import require_valid_legacy_topic_question_backfill_packet
    from brain.v5.legacy_l2_graph_contracts import require_valid_legacy_l2_graph_manifest
    from brain.v5.legacy_l2_seed_audit_contracts import require_valid_canonical_legacy_l2_seed_audit
    from brain.v5.legacy_l2_seed_review_worklist_contracts import (
        require_valid_canonical_legacy_l2_seed_review_worklist,
        require_valid_legacy_l2_seed_group_review_result_record,
    )
    from brain.v5.legacy_l2_obsidian_contracts import require_valid_legacy_l2_obsidian_view_bundle
    from brain.v5.legacy_l2_typed_migration_contracts import require_valid_legacy_l2_typed_migration_packet
    from brain.v5.legacy_migration_audit_contracts import require_valid_legacy_migration_coverage_audit
    from brain.v5.legacy_runtime_log_audit_contracts import require_valid_legacy_runtime_log_marker_audit
    from brain.v5.legacy_source_metadata_repair_contracts import require_valid_legacy_source_metadata_repair_packet
    from brain.v5.legacy_source_reconstruction_contracts import (
        require_valid_legacy_source_reconstruction_apply,
        require_valid_legacy_source_reconstruction_manifest,
        require_valid_legacy_source_reconstruction_plan,
        require_valid_legacy_source_reconstruction_review_packet,
    )
    from brain.v5.legacy_source_reconstruction_obsidian_contracts import require_valid_legacy_source_reconstruction_obsidian_view_bundle
    from brain.v5.source_reconstruction_contracts import (
        require_valid_source_reconstruction_manifest,
        require_valid_source_reconstruction_review_manifest,
        require_valid_source_reconstruction_review_packet,
        require_valid_source_reconstruction_review_result_record,
        require_valid_source_stack_coverage_manifest,
    )
    from brain.v5.source_reconstruction_obsidian_contracts import require_valid_source_reconstruction_obsidian_view_bundle
    from brain.v5.legacy_semantic_review_contracts import (
        require_valid_legacy_semantic_review_manifest,
        require_valid_legacy_semantic_review_packet,
        require_valid_legacy_semantic_repair_apply,
        require_valid_legacy_semantic_repair_plan,
        require_valid_legacy_semantic_review_queue,
        require_valid_legacy_semantic_review_result_record,
    )
    from brain.v5.legacy_semantic_repair_manifest_contracts import require_valid_legacy_semantic_repair_manifest
    from brain.v5.legacy_semantic_needs_revision_packet_contracts import require_valid_legacy_semantic_needs_revision_basis_packet
    from brain.v5.legacy_semantic_needs_revision_contracts import require_valid_legacy_semantic_needs_revision_basis_queue
    from brain.v5.legacy_semantic_needs_revision_obsidian_contracts import require_valid_legacy_semantic_needs_revision_basis_obsidian_view_bundle
    from brain.v5.legacy_semantic_worklist_contracts import require_valid_legacy_semantic_review_worklist
    from brain.v5.legacy_semantic_review_obsidian_contracts import require_valid_legacy_semantic_review_obsidian_view_bundle
    from brain.v5.host_readiness_contracts import (
        require_valid_runtime_host_production_loop_audit,
        require_valid_runtime_host_readiness_audit,
    )
    from brain.v5.host_lifecycle_contracts import require_valid_runtime_host_lifecycle_audit
    from brain.v5.runtime_payload_profile_contracts import require_valid_runtime_payload_profiles
    from brain.v5.curated_rag_contracts import (
        require_valid_curated_rag_chunk,
        require_valid_curated_rag_corpus,
        require_valid_curated_rag_ingest_result,
        require_valid_curated_rag_promotion_draft,
        require_valid_curated_rag_search_result,
    )
    from brain.v5.interaction_preview_contracts import require_valid_interaction_recording_preview
    from brain.v5.interaction_worklist_contracts import require_valid_interaction_recording_worklist
    from brain.v5.workspace_interaction_preview_contracts import require_valid_workspace_interaction_preview_bundle
    from brain.v5.vnext_readiness_contracts import require_valid_vnext_readiness_manifest
    from brain.v5.literature_intake_contracts import (
        require_valid_literature_intake_record_result,
        require_valid_literature_intake_suggestion,
    )
    from brain.v5.literature_comparison_draft_contracts import (
        require_valid_literature_comparison_draft,
    )
    from brain.v5.literature_source_review_handoff_contracts import (
        require_valid_literature_source_review_handoff,
    )
    from brain.v5.lane_exemplar_contracts import (
        require_valid_lane_exemplar_manifest,
        require_valid_lane_exemplar_record,
    )
    from brain.v5.obsidian_view_contracts import require_valid_l2_obsidian_view_bundle
    from brain.v5.workspace_refresh_contracts import require_valid_workspace_refresh_bundle
    from brain.v5.workspace_file_migration_ledger_contracts import (
        require_valid_workspace_file_migration_ledger,
        require_valid_workspace_file_migration_ledger_progress,
    )
    from brain.v5.workspace_migration_health_contracts import require_valid_workspace_migration_health
    from brain.v5.workspace_old_store_import_contracts import require_valid_workspace_old_store_import_result
    from brain.v5.workspace_recovery_binding_repair_contracts import require_valid_workspace_recovery_binding_repair
    from brain.v5.workspace_recovery_audit_contracts import (
        require_valid_workspace_recovery_audit,
        require_valid_workspace_recovery_audit_progress,
    )
    from brain.v5.workspace_recording_audit_contracts import require_valid_workspace_recording_audit
    from brain.v5.qsgw_cockpit_contracts import require_valid_qsgw_cockpit_bundle
    from brain.v5.research_cockpit_contracts import require_valid_research_cockpit_bundle
    from brain.v5.moment_policy_contracts import require_valid_host_agnostic_moment_policy
    from brain.v5.goal_continuation_contracts import (
        require_valid_goal_continuation_list,
        require_valid_goal_continuation_packet,
    )
    from brain.v5.hook_protocol_contracts import (
        require_valid_claude_code_hook_installation,
        require_valid_claude_code_hook_settings,
        require_valid_hook_trace_event_record,
        require_valid_opencode_plugin_bridge,
        require_valid_pre_tool_policy_decision,
    )
    from brain.v5.hook_kimi_contracts import (
        require_valid_kimi_code_hook_config,
        require_valid_kimi_code_hook_installation,
    )
    from brain.v5.hook_install_contracts import (
        require_valid_codex_hook_installation,
        require_valid_opencode_hook_installation,
    )
    from brain.v5.recording_navigator_contracts import (
        require_valid_recording_candidate_classification,
        require_valid_recording_effect_verification,
        require_valid_recording_navigation_state,
        require_valid_recording_slot_expansion,
    )

    return {
        "adapter_packet": require_valid_adapter_packet,
        "adapter_protocol_registry": require_valid_adapter_protocol_registry,
        "artifact_record": require_valid_artifact_record,
        "bounded_numerical_evidence_bundle": require_valid_bounded_numerical_evidence_bundle,
        "claim_status_record": require_valid_claim_status_record,
        "claim_relation_map": require_valid_claim_relation_map,
        "claim_trust_audit": require_valid_claim_trust_audit,
        "claude_code_hook_installation": require_valid_claude_code_hook_installation,
        "claude_code_hook_settings": require_valid_claude_code_hook_settings,
        "codex_hook_bridge": require_valid_codex_hook_bridge,
        "codex_hook_installation": require_valid_codex_hook_installation,
        "code_state_record": require_valid_code_state_record,
        "curated_rag_chunk": require_valid_curated_rag_chunk,
        "curated_rag_corpus": require_valid_curated_rag_corpus,
        "curated_rag_ingest_result": require_valid_curated_rag_ingest_result,
        "curated_rag_promotion_draft": require_valid_curated_rag_promotion_draft,
        "curated_rag_search_result": require_valid_curated_rag_search_result,
        "evidence_record": require_valid_evidence_record,
        "lifecycle_event_record": require_valid_lifecycle_event_record,
        "execution_brief": require_valid_execution_brief,
        "exploratory_record": require_valid_exploratory_record,
        "failure_mode_audit": require_valid_failure_mode_audit,
        "failure_mode_review_packet": require_valid_failure_mode_review_packet,
        "failure_mode_review_result_record": require_valid_failure_mode_review_result_record,
        "final_engineering_readiness_audit": require_valid_final_engineering_readiness_audit,
        "final_output_profile": require_valid_final_output_profile,
        "human_checkpoint_record": require_valid_human_checkpoint_record,
        "hook_trace_event_record": require_valid_hook_trace_event_record,
        "interaction_recording_preview": require_valid_interaction_recording_preview,
        "interaction_recording_worklist": require_valid_interaction_recording_worklist,
        "workspace_interaction_preview_bundle": require_valid_workspace_interaction_preview_bundle,
        "literature_comparison_draft": require_valid_literature_comparison_draft,
        "literature_intake_record_result": require_valid_literature_intake_record_result,
        "literature_intake_suggestion": require_valid_literature_intake_suggestion,
        "literature_source_review_handoff": require_valid_literature_source_review_handoff,
        "kimi_code_hook_config": require_valid_kimi_code_hook_config,
        "kimi_code_hook_installation": require_valid_kimi_code_hook_installation,
        "knowledge_connector_catalog": require_valid_knowledge_connector_catalog,
        "lane_exemplar_manifest": require_valid_lane_exemplar_manifest,
        "lane_exemplar_record": require_valid_lane_exemplar_record,
        "l2_obsidian_view_bundle": require_valid_l2_obsidian_view_bundle,
        "l2_memory_audit": require_valid_l2_memory_audit,
        "legacy_executable_evidence_packet": require_valid_legacy_executable_evidence_packet,
        "legacy_human_checkpoint_obsidian_view_bundle": require_valid_legacy_human_checkpoint_obsidian_view_bundle,
        "legacy_human_checkpoint_packet": require_valid_legacy_human_checkpoint_packet,
        "legacy_topic_question_backfill_packet": require_valid_legacy_topic_question_backfill_packet,
        "legacy_l2_graph_manifest": require_valid_legacy_l2_graph_manifest,
        "canonical_legacy_l2_seed_audit": require_valid_canonical_legacy_l2_seed_audit,
        "canonical_legacy_l2_seed_review_worklist": require_valid_canonical_legacy_l2_seed_review_worklist,
        "legacy_l2_seed_group_review_result_record": require_valid_legacy_l2_seed_group_review_result_record,
        "legacy_l2_obsidian_view_bundle": require_valid_legacy_l2_obsidian_view_bundle,
        "legacy_l2_typed_migration_packet": require_valid_legacy_l2_typed_migration_packet,
        "legacy_migration_coverage_audit": require_valid_legacy_migration_coverage_audit,
        "legacy_migration_result": require_valid_legacy_migration_result,
        "legacy_runtime_log_marker_audit": require_valid_legacy_runtime_log_marker_audit,
        "legacy_source_metadata_repair_packet": require_valid_legacy_source_metadata_repair_packet,
        "legacy_source_reconstruction_apply": require_valid_legacy_source_reconstruction_apply,
        "legacy_source_reconstruction_manifest": require_valid_legacy_source_reconstruction_manifest,
        "legacy_source_reconstruction_obsidian_view_bundle": require_valid_legacy_source_reconstruction_obsidian_view_bundle,
        "legacy_source_reconstruction_plan": require_valid_legacy_source_reconstruction_plan,
        "legacy_source_reconstruction_review_packet": require_valid_legacy_source_reconstruction_review_packet,
        "legacy_semantic_needs_revision_basis_obsidian_view_bundle": require_valid_legacy_semantic_needs_revision_basis_obsidian_view_bundle,
        "legacy_semantic_needs_revision_basis_packet": require_valid_legacy_semantic_needs_revision_basis_packet,
        "legacy_semantic_needs_revision_basis_queue": require_valid_legacy_semantic_needs_revision_basis_queue,
        "legacy_semantic_review_manifest": require_valid_legacy_semantic_review_manifest,
        "legacy_semantic_review_obsidian_view_bundle": require_valid_legacy_semantic_review_obsidian_view_bundle,
        "legacy_semantic_review_packet": require_valid_legacy_semantic_review_packet,
        "legacy_semantic_review_worklist": require_valid_legacy_semantic_review_worklist,
        "legacy_semantic_repair_apply": require_valid_legacy_semantic_repair_apply,
        "legacy_semantic_repair_manifest": require_valid_legacy_semantic_repair_manifest,
        "legacy_semantic_repair_plan": require_valid_legacy_semantic_repair_plan,
        "legacy_semantic_review_result_record": require_valid_legacy_semantic_review_result_record,
        "legacy_semantic_review_queue": require_valid_legacy_semantic_review_queue,
        "memory_entry_record": require_valid_memory_entry_record,
        "object_relation_record": require_valid_object_relation_record,
        "operator_checkpoint_record": require_valid_operator_checkpoint_record,
        "opencode_hook_installation": require_valid_opencode_hook_installation,
        "opencode_plugin_bridge": require_valid_opencode_plugin_bridge,
        "host_agnostic_moment_policy": require_valid_host_agnostic_moment_policy,
        "physics_object_record": require_valid_physics_object_record,
        "pre_tool_policy_decision": require_valid_pre_tool_policy_decision,
        "process_graph_slice": require_valid_process_graph_slice,
        "promotion_packet_record": require_valid_promotion_packet_record,
        "proof_obligation_record": require_valid_proof_obligation_record,
        "qsgw_cockpit_bundle": require_valid_qsgw_cockpit_bundle,
        "record_gate_coverage_audit": require_valid_record_gate_coverage_audit,
        "recording_candidate_classification": require_valid_recording_candidate_classification,
        "recording_effect_verification": require_valid_recording_effect_verification,
        "recording_navigation_state": require_valid_recording_navigation_state,
        "recording_slot_expansion": require_valid_recording_slot_expansion,
        "record_ref_lookup": require_valid_record_ref_lookup,
        "reference_location_record": require_valid_reference_location_record,
        "research_route_record": require_valid_research_route_record,
        "research_run_event_record": require_valid_research_run_event_record,
        "research_run_record": require_valid_research_run_record,
        "research_event_classification": require_valid_research_event_classification,
        "research_cockpit_bundle": require_valid_research_cockpit_bundle,
        "research_intent_packet": require_valid_research_intent_packet,
        "run_iteration_record": require_valid_run_iteration_record,
        "runtime_hook_installation_audit": require_valid_runtime_hook_installation_audit,
        "runtime_host_lifecycle_audit": require_valid_runtime_host_lifecycle_audit,
        "runtime_host_production_loop_audit": require_valid_runtime_host_production_loop_audit,
        "runtime_host_readiness_audit": require_valid_runtime_host_readiness_audit,
        "runtime_bridge_target_manifest": require_valid_runtime_bridge_target_manifest,
        "runtime_mcp_bridge_acceptance": require_valid_runtime_mcp_bridge_acceptance,
        "runtime_payload_profiles": require_valid_runtime_payload_profiles,
        "runtime_hook_installation_paths": require_valid_runtime_hook_installation_paths,
        "runtime_hook_smoke_coverage": require_valid_runtime_hook_smoke_coverage,
        "sensemaking_report_record": require_valid_sensemaking_report_record,
        "session_summary_bundle": require_valid_session_summary_bundle,
        "source_reconstruction_audit": require_valid_source_reconstruction_audit,
        "source_asset_record": require_valid_source_asset_record,
        "source_stack_coverage_manifest": require_valid_source_stack_coverage_manifest,
        "source_reconstruction_manifest": require_valid_source_reconstruction_manifest,
        "source_reconstruction_obsidian_view_bundle": require_valid_source_reconstruction_obsidian_view_bundle,
        "source_reconstruction_review_manifest": require_valid_source_reconstruction_review_manifest,
        "source_reconstruction_review_packet": require_valid_source_reconstruction_review_packet,
        "source_reconstruction_review_result_record": require_valid_source_reconstruction_review_result_record,
        "steering_decision_record": require_valid_steering_decision_record,
        "strategy_memory_record": require_valid_strategy_memory_record,
        "summary_orientation": require_valid_summary_orientation,
        "tool_executor_catalog": require_valid_tool_executor_catalog,
        "topic_status_bundle": require_valid_topic_status_bundle,
        "tool_recipe_record": require_valid_tool_recipe_record,
        "tool_run_record": require_valid_tool_run_record,
        "trust_update_record": require_valid_trust_update_record,
        "trust_update_apply": require_valid_trust_update_apply,
        "trust_update_preflight": require_valid_trust_update_preflight,
        "validation_contract_record": require_valid_validation_contract_record,
        "validation_result_record": require_valid_validation_result_record,
        "vnext_readiness_manifest": require_valid_vnext_readiness_manifest,
        "workspace_summary_bundle": require_valid_workspace_summary_bundle,
        "workspace_replay_packet": require_valid_workspace_replay_packet,
        "workspace_refresh_bundle": require_valid_workspace_refresh_bundle,
        "workspace_file_migration_ledger": require_valid_workspace_file_migration_ledger,
        "workspace_file_migration_ledger_progress": require_valid_workspace_file_migration_ledger_progress,
        "workspace_migration_health": require_valid_workspace_migration_health,
        "workspace_old_store_import_result": require_valid_workspace_old_store_import_result,
        "workspace_recovery_binding_repair": require_valid_workspace_recovery_binding_repair,
        "workspace_recovery_audit": require_valid_workspace_recovery_audit,
        "workspace_recovery_audit_progress": require_valid_workspace_recovery_audit_progress,
        "workspace_recording_audit": require_valid_workspace_recording_audit,
        "goal_continuation_packet": require_valid_goal_continuation_packet,
        "goal_continuation_list": require_valid_goal_continuation_list,
    }
