# Compatibility shard 2 for cli.
from __future__ import annotations

def _add_parser_section_02(sp):
    gp = sp.add_parser("graph")
    gs = gp.add_subparsers(dest="graph_command", required=True)
    sl = gs.add_parser("slice")
    sl.add_argument("session_id")
    sl.add_argument("--claim", default="", dest="claim_id")
    sl.add_argument("--limit", type=int, default=80)
    mp = gs.add_parser("moment-policy")
    mp.add_argument("session_id")
    mp.add_argument("--claim", default="", dest="claim_id")
    mp.add_argument("--limit", type=int, default=80)
    recp = sp.add_parser("recording")
    recs = recp.add_subparsers(dest="recording_command", required=True)
    rcc = recs.add_parser("classify-candidate")
    rcc.add_argument("--session", default="", dest="session_id")
    rcc.add_argument("--event-type", required=True)
    rcc.add_argument("--summary", default="")
    rcc.add_argument("--topic", default="", dest="topic_id")
    rcc.add_argument("--claim", default="", dest="claim_id")
    rcc.add_argument("--touched-ref", action="append", default=[], dest="touched_refs")
    rcc.add_argument("--produced-artifact", action="append", default=[], dest="produced_artifacts")
    rcc.add_argument("--tool-call-id", default="")
    rcc.add_argument("--risk-hint", default="")
    rcc.add_argument("--payload-json", default="{}")
    rns = recs.add_parser("navigation-state")
    rns.add_argument("session_id")
    rns.add_argument("--claim", default="", dest="claim_id")
    rns.add_argument("--limit", type=int, default=40)
    res = recs.add_parser("expand-slot")
    res.add_argument("session_id")
    res.add_argument("--slot", required=True)
    res.add_argument("--claim", default="", dest="claim_id")
    res.add_argument("--candidate-json", default="{}")
    rev = recs.add_parser("verify-effect")
    rev.add_argument("session_id")
    rev.add_argument("--claim", default="", dest="claim_id")
    rev.add_argument("--expected-ref", action="append", default=[], dest="expected_refs")
    rev.add_argument("--before-node-id", action="append", default=[], dest="before_node_ids")
    rev.add_argument("--before-edge-id", action="append", default=[], dest="before_edge_ids")
    rev.add_argument("--limit", type=int, default=80)
    rlp = recs.add_parser("plan-lightweight-write")
    rlp.add_argument("--topic", required=True, dest="topic_id")
    rlp.add_argument("--session", required=True, dest="current_session_id")
    rlp.add_argument("--summary", required=True, dest="event_summary")
    rlp.add_argument("--active-claim", default="", dest="active_claim_id")
    rlp.add_argument("--target-claim-hint", default="")
    rlp.add_argument("--touched-file", action="append", default=[], dest="touched_files_or_artifacts")
    rlp.add_argument("--touched-ref", action="append", default=[], dest="touched_tool_runs_or_evidence_refs")
    rlp.add_argument("--risk-hint", default="")
    rp = sp.add_parser("risk")
    rs = rp.add_subparsers(dest="risk_command", required=True)
    rs.add_parser("assess").add_argument("claim_id")
    cp = sp.add_parser("code")
    cs = cp.add_subparsers(dest="code_command", required=True)
    cst = cs.add_parser("state")
    css = cst.add_subparsers(dest="code_state_command", required=True)
    csr = css.add_parser("record")
    csr.add_argument("--repo-id", required=True)
    csr.add_argument("--upstream-remote", required=True)
    csr.add_argument("--upstream-branch", required=True)
    csr.add_argument("--upstream-commit", required=True)
    csr.add_argument("--local-branch", required=True)
    csr.add_argument("--worktree-path", required=True)
    csr.add_argument("--dirty", action="store_true")
    csr.add_argument("--patch-id", default="")
    csr.add_argument("--diff-hash", default="")
    csr.add_argument("--build-config-json", default="{}")
    csr.add_argument("--runtime-environment-json", default="{}")
    csr.add_argument("--linked-records-json", default="{}")
    csr.add_argument("--known-divergence", default="")
    csa = css.add_parser("auto")
    csa.add_argument("--worktree-path", required=True)
    csa.add_argument("--repo-id", default="")
    csa.add_argument("--topic", default="", dest="topic_id")
    csa.add_argument("--claim", default="", dest="claim_id")
    csa.add_argument("--session", default="", dest="session_id")
    csa.add_argument("--build-config-json", default="{}")
    csa.add_argument("--runtime-environment-json", default="{}")
    csa.add_argument("--linked-records-json", default="{}")
    csa.add_argument("--known-divergence", default="")
    csa.add_argument("--write-patch-artifact", action="store_true")
    add_evidence_parser(sp)
    tlp = sp.add_parser("tool")
    tls = tlp.add_subparsers(dest="tool_command", required=True)
    tls.add_parser("executors")
    trp = tls.add_parser("recipe")
    trs = trp.add_subparsers(dest="tool_recipe_command", required=True)
    tr = trs.add_parser("register")
    tr.add_argument("recipe_id")
    tr.add_argument("--family", required=True, dest="tool_family")
    tr.add_argument("--name", required=True, dest="tool_name")
    tr.add_argument("--purpose", required=True)
    tr.add_argument("--required-input", action="append", default=[], dest="required_inputs")
    tr.add_argument("--expected-output", action="append", default=[], dest="expected_outputs")
    tr.add_argument("--invariant", action="append", default=[], dest="invariants")
    trun = tls.add_parser("run")
    trus = trun.add_subparsers(dest="tool_run_command", required=True)
    trr = trus.add_parser("record")
    trr.add_argument("--recipe", required=True, dest="recipe_id")
    trr.add_argument("--family", required=True, dest="tool_family")
    trr.add_argument("--name", required=True, dest="tool_name")
    trr.add_argument("--topic", required=True, dest="topic_id")
    trr.add_argument("--claim", required=True, dest="claim_id")
    trr.add_argument("--inputs-json", default="{}")
    trr.add_argument("--outputs-json", default="{}")
    trr.add_argument("--environment-json", default="{}")
    trr.add_argument("--evidence-status", default="unreviewed")
    trr.add_argument("--inputs-json-file", default="")
    trr.add_argument("--outputs-json-file", default="")
    trr.add_argument("--environment-json-file", default="")
    trr.add_argument("--code-state-id", action="append", default=[], dest="code_state_ids")
    trr.add_argument("--artifact-id", action="append", default=[], dest="artifact_ids")
    trr.add_argument("--source-ref", action="append", default=[], dest="source_refs")
    trr.add_argument("--scientific-run-id", default="")
    trr.add_argument("--supersedes", default="")
    trr.add_argument("--lane", choices=("final", "diagnostic", "exploratory"), default="diagnostic")
    tra = trus.add_parser("capture-auto")
    tra.add_argument("--path", required=True)
    tra.add_argument("--recipe", required=True, dest="recipe_id")
    tra.add_argument("--family", required=True, dest="tool_family")
    tra.add_argument("--name", required=True, dest="tool_name")
    tra.add_argument("--topic", required=True, dest="topic_id")
    tra.add_argument("--claim", required=True, dest="claim_id")
    tra.add_argument("--inputs-json", default="{}")
    tra.add_argument("--outputs-json", default="{}")
    tra.add_argument("--environment-json", default="{}")
    tra.add_argument("--inputs-json-file", default="")
    tra.add_argument("--outputs-json-file", default="")
    tra.add_argument("--environment-json-file", default="")
    tra.add_argument("--evidence-status", default="unreviewed")
    tra.add_argument("--code-state-id", action="append", default=[], dest="code_state_ids")
    tra.add_argument("--artifact-id", action="append", default=[], dest="artifact_ids")
    tra.add_argument("--source-ref", action="append", default=[], dest="source_refs")
    tra.add_argument("--scientific-run-id", default="")
    tra.add_argument("--supersedes", default="")
    tra.add_argument("--lane", choices=("final", "diagnostic", "exploratory"), default="diagnostic")
    tra.add_argument("--summary", default="")
    tra.add_argument("--max-preview-chars", type=int, default=1200)
    te = tls.add_parser("execute")
    te.add_argument("executor_id")
    te.add_argument("--recipe", required=True, dest="recipe_id")
    te.add_argument("--topic", required=True, dest="topic_id")
    te.add_argument("--claim", required=True, dest="claim_id")
    te.add_argument("--inputs-json", default="{}")
    te.add_argument("--inputs-json-file", default="")
    te.add_argument("--evidence-status", default="")
    te.add_argument("--evidence-type", default="tool_run")
    te.add_argument("--evidence-summary", default="")
    te.add_argument("--code-state-id", action="append", default=[], dest="code_state_ids")
    te.add_argument("--artifact-id", action="append", default=[], dest="artifact_ids")
    te.add_argument("--source-ref", action="append", default=[], dest="source_refs")
    te.add_argument("--supports-output", action="append", default=[], dest="supports_outputs")

def _add_parser_section_03(sp):
    kp = sp.add_parser("knowledge")
    ks = kp.add_subparsers(dest="knowledge_command", required=True)
    ks.add_parser("connectors")
    kb = ks.add_parser("bindings")
    kb.add_argument("--connector", default="", dest="connector_id")
    kb.add_argument("--include-connectors", action="store_true")
    kbind = ks.add_parser("bind")
    kbind.add_argument("--connector", required=True, dest="connector_id")
    kbind.add_argument("--root", required=True, dest="root_uri")
    kbind.add_argument("--corpus-id", default="")
    kbind.add_argument("--label", default="")
    kbind.add_argument("--glob", action="append", default=[], dest="file_globs")
    kbind.add_argument("--domain-hint", action="append", default=[], dest="domain_hints")
    kbind.add_argument("--topic-hint", action="append", default=[], dest="topic_hints")
    kbind.add_argument("--priority", default="medium")
    kbind.add_argument("--status", default="active")
    kbind.add_argument("--notes", default="")
    add_domain_pack_parser(sp)
    add_query_parser(sp)
    add_context_parser(sp)
    crp = sp.add_parser("curated-rag")
    crs = crp.add_subparsers(dest="curated_rag_command", required=True)
    crs.add_parser("catalog")
    crs_search = crs.add_parser("search")
    crs_search.add_argument("query")
    crs_search.add_argument("--limit", type=int, default=5)
    crs_chunk = crs.add_parser("chunk")
    crs_chunk.add_argument("chunk_id")
    crs_promo = crs.add_parser("promotion-draft")
    crs_promo.add_argument("chunk_id")
    crs_promo.add_argument("--topic", default="", dest="topic_id")
    crs_promo.add_argument("--claim", default="", dest="claim_id")
    crs_promo.add_argument("--connector", default="curated_rag", dest="connector_id")
    crs_promo.add_argument("--intent", default="claim_support_review", dest="promotion_intent")
    cri = crs.add_parser("ingest")
    cri.add_argument("--path", action="append", required=True, dest="paths")
    cri.add_argument("--corpus-id", default="")
    cri.add_argument("--tag", action="append", default=[], dest="tags")
    cri.add_argument("--domain-hint", action="append", default=[], dest="domain_hints")
    cri.add_argument("--topic-hint", action="append", default=[], dest="topic_hints")
    cri.add_argument("--language", default="en")
    cri.add_argument("--priority", default="medium")
    cri.add_argument("--chunk-token-limit", type=int, default=220)
    cri.add_argument("--title-prefix", default="")
    cri.add_argument("--asset-type", default="")
    cri.add_argument("--no-rebuild-index", action="store_true")
    trcp = sp.add_parser("trace")
    trcs = trcp.add_subparsers(dest="trace_command", required=True)
    the = trcs.add_parser("hook-event")
    thes = the.add_subparsers(dest="trace_hook_event_command", required=True)
    thp = thes.add_parser("persist")
    thp.add_argument("--payload-json", required=True)
    rfp = sp.add_parser("reference")
    rfs = rfp.add_subparsers(dest="reference_command", required=True)
    rfl = rfs.add_parser("location")
    rls = rfl.add_subparsers(dest="reference_location_command", required=True)
    rlr = rls.add_parser("record")
    rlr.add_argument("--topic", required=True, dest="topic_id")
    rlr.add_argument("--claim", default="", dest="claim_id")
    rlr.add_argument("--connector", required=True, dest="connector_id")
    rlr.add_argument("--type", required=True, dest="location_type")
    rlr.add_argument("--uri", required=True)
    rlr.add_argument("--label", required=True)
    rlr.add_argument("--source-ref", default="")
    rlr.add_argument("--external-id", default="")
    rlr.add_argument("--status", default="located")
    rlr.add_argument("--summary", default="")
    rlr.add_argument("--metadata-json", default="{}")
    rlr.add_argument("--linked-records-json", default="{}")
    add_legacy_parser(sp)
    add_interaction_parser(sp)
    add_literature_parser(sp)
    add_vnext_parsers(sp)
    add_goal_parser(sp)
    add_harness_feedback_parser(sp)
    add_summary_parser(sp)
    add_source_parser(sp)
    add_adapter_parser(sp)
    op = sp.add_parser("object")
    ops = op.add_subparsers(dest="object_command", required=True)
    orr = ops.add_parser("record")
    orr.add_argument("--topic", required=True, dest="topic_id")
    orr.add_argument("--type", required=True, dest="object_type")
    orr.add_argument("--name", required=True)
    orr.add_argument("--definition", required=True)
    orr.add_argument("--notation", default="")
    orr.add_argument("--assumption", action="append", default=[], dest="assumptions")
    orr.add_argument("--source-ref", action="append", default=[], dest="source_refs")
    orr.add_argument("--metadata-json", default="{}")
    orr.add_argument("--linked-records-json", default="{}")
    orr.add_argument("--status", default="active")
    rlp = sp.add_parser("relation")
    rls2 = rlp.add_subparsers(dest="relation_command", required=True)
    rr = rls2.add_parser("record")
    rr.add_argument("--topic", required=True, dest="topic_id")
    rr.add_argument("--type", required=True, dest="relation_type")
    rr.add_argument("--subject", required=True, dest="subject_id")
    rr.add_argument("--object", required=True, dest="object_id")
    rr.add_argument("--statement", required=True)
    rr.add_argument("--claim", default="", dest="claim_id")
    rr.add_argument("--assumption", action="append", default=[], dest="assumptions")
    rr.add_argument("--failure-mode", action="append", default=[], dest="failure_modes")
    rr.add_argument("--source-ref", action="append", default=[], dest="source_refs")
    rr.add_argument("--evidence-ref", action="append", default=[], dest="evidence_refs")
    rr.add_argument("--status", default="hypothesis")
    sg_p = sp.add_parser("sensemaking")
    sg_s = sg_p.add_subparsers(dest="sensemaking_command", required=True)
    sr = sg_s.add_parser("report")
    sr.add_argument("--topic", required=True, dest="topic_id")
    sr.add_argument("--claim", required=True, dest="claim_id")
    sr.add_argument("--title", required=True)
    sr.add_argument("--summary", required=True)
    sr.add_argument("--object-id", action="append", default=[], dest="object_ids")
    sr.add_argument("--relation-id", action="append", default=[], dest="relation_ids")
    sr.add_argument("--evidence-ref", action="append", default=[], dest="evidence_refs")
    sr.add_argument("--open-question", action="append", default=[], dest="open_questions")
    sr.add_argument("--next-action", action="append", default=[], dest="next_actions")
    ex_p = sp.add_parser("exploration")
    ex_s = ex_p.add_subparsers(dest="exploration_command", required=True)
    er = ex_s.add_parser("record")
    er.add_argument("--topic", required=True, dest="topic_id")
    er.add_argument("--claim", default="", dest="claim_id")
    er.add_argument("--session", default="", dest="session_id")
    er.add_argument("--type", required=True, dest="exploration_type")
    er.add_argument("--title", required=True)
    er.add_argument("--focal-question", required=True)
    er.add_argument("--summary", required=True)
    er.add_argument("--original-question", default="")
    er.add_argument("--local-question", default="")
    er.add_argument("--status", default="open")
    er.add_argument("--object-id", action="append", default=[], dest="object_ids")
    er.add_argument("--relation-id", action="append", default=[], dest="relation_ids")
    er.add_argument("--source-ref", action="append", default=[], dest="source_refs")
    er.add_argument("--artifact-id", action="append", default=[], dest="artifact_ids")
    er.add_argument("--parent-record-id", action="append", default=[], dest="parent_record_ids")
    er.add_argument("--derived-record-id", action="append", default=[], dest="derived_record_ids")
    er.add_argument("--reasoning-move", action="append", default=[], dest="reasoning_moves")
    er.add_argument("--backtrace-target", action="append", default=[], dest="backtrace_targets")
    er.add_argument("--candidate-path", action="append", default=[], dest="candidate_paths")
    er.add_argument("--relation-path-question", action="append", default=[], dest="relation_path_questions")
    er.add_argument("--definition-boundary-question", action="append", default=[], dest="definition_boundary_questions")
    er.add_argument("--derivation-backtrace-question", action="append", default=[], dest="derivation_backtrace_questions")
    er.add_argument("--source-dependency-question", action="append", default=[], dest="source_dependency_questions")
    er.add_argument("--original-question-guard", action="append", default=[], dest="original_question_guard")
    er.add_argument("--unresolved-point", action="append", default=[], dest="unresolved_points")
    er.add_argument("--next-action", action="append", default=[], dest="next_actions")
    er.add_argument("--human-steering", default="")
    er.add_argument("--metadata-json", default="{}")

def _add_parser_section_04(sp):
    rt_p = sp.add_parser("route")
    rt_s = rt_p.add_subparsers(dest="route_command", required=True)
    rtr = rt_s.add_parser("record")
    rtr.add_argument("--topic", required=True, dest="topic_id")
    rtr.add_argument("--claim", default="", dest="claim_id")
    rtr.add_argument("--session", default="", dest="session_id")
    rtr.add_argument("--type", required=True, dest="route_type")
    rtr.add_argument("--status", required=True)
    rtr.add_argument("--title", required=True)
    rtr.add_argument("--rationale", required=True)
    rtr.add_argument("--current-question", default="")
    rtr.add_argument("--next-action", default="")
    rtr.add_argument("--failure-mode", action="append", default=[], dest="failure_modes")
    rtr.add_argument("--source-ref", action="append", default=[], dest="source_refs")
    rtr.add_argument("--evidence-ref", action="append", default=[], dest="evidence_refs")
    rtr.add_argument("--artifact-id", action="append", default=[], dest="artifact_ids")
    rtr.add_argument("--parent-route-id", action="append", default=[], dest="parent_route_ids")
    rtr.add_argument("--checkpoint-id", action="append", default=[], dest="checkpoint_ids")
    rtr.add_argument("--exploratory-record-id", action="append", default=[], dest="exploratory_record_ids")
    rtr.add_argument("--object-id", action="append", default=[], dest="object_ids")
    rtr.add_argument("--relation-id", action="append", default=[], dest="relation_ids")
    rtr.add_argument("--decision-rationale", default="")
    rtr.add_argument("--pivot-reason", default="")
    rtr.add_argument("--metadata-json", default="{}")
    sap = sp.add_parser("subagent")
    sas = sap.add_subparsers(dest="subagent_command", required=True)
    sai = sas.add_parser("ingest-result")
    sai.add_argument("--topic", required=True, dest="topic_id")
    sai.add_argument("--packet-json", required=True)
    sai.add_argument("--result-json", required=True)
    chk_p = sp.add_parser("checkpoint")
    chk_s = chk_p.add_subparsers(dest="checkpoint_command", required=True)
    chk_r = chk_s.add_parser("request")
    chk_r.add_argument("--topic", required=True, dest="topic_id")
    chk_r.add_argument("--claim", required=True, dest="claim_id")
    chk_r.add_argument("--reason", required=True)
    chk_r.add_argument("--requested-by", required=True)
    chk_r.add_argument("--option", action="append", default=[], dest="options")
    chk_d = chk_s.add_parser("decide")
    chk_d.add_argument("checkpoint_id")
    chk_d.add_argument("--decision", required=True)
    chk_d.add_argument("--rationale", required=True)
    chk_d.add_argument("--decided-by", required=True)
    chk_preview = chk_s.add_parser("preview-batch")
    _add_quiet_checkpoint_args(chk_preview)
    chk_apply = chk_s.add_parser("apply-batch")
    _add_quiet_checkpoint_args(chk_apply)
    pp = sp.add_parser("promotion")
    pps = pp.add_subparsers(dest="promotion_command", required=True)
    pkt = pps.add_parser("packet")
    pkts = pkt.add_subparsers(dest="promotion_packet_command", required=True)
    pc = pkts.add_parser("create")
    pc.add_argument("--topic", required=True, dest="topic_id")
    pc.add_argument("--claim", required=True, dest="claim_id")
    pc.add_argument("--proposed-kind", default="scoped_claim", dest="proposed_memory_kind")
    pc.add_argument("--scope", required=True)
    pc.add_argument("--evidence-ref", action="append", default=[], dest="evidence_refs")
    pc.add_argument("--validation-result-id", action="append", default=[], dest="validation_result_ids")
    pc.add_argument("--non-claim", action="append", default=[], dest="non_claims")
    pc.add_argument("--failure-mode", action="append", default=[], dest="known_failure_modes")
    pc.add_argument("--failure-mode-review-checkpoint", default="", dest="failure_mode_review_checkpoint_id")
    pc.add_argument("--failure-mode-review-result", default="", dest="failure_mode_review_result_id")
    pa = pkts.add_parser("apply")
    pa.add_argument("packet_id")
    pa.add_argument("--checkpoint", required=True, dest="checkpoint_id")
    tp2 = sp.add_parser("trust")
    ts2 = tp2.add_subparsers(dest="trust_command", required=True)
    _add_trust_request_args(ts2.add_parser("preflight"))
    _add_trust_request_args(ts2.add_parser("apply"))
    ta = ts2.add_parser("audit")
    ta.add_argument("--claim", required=True, dest="claim_id")
    tur = ts2.add_parser("update-record")
    tur.add_argument("update_id")
    add_policy_parser(sp)
    add_validation_parser(sp)
    add_memory_parser(sp)
    add_research_state_parser(sp)
    add_authority_parser(sp)
    rp_lifecycle = sp.add_parser("record")
    rps = rp_lifecycle.add_subparsers(dest="record_command", required=True)
    rh = rps.add_parser("rehome")
    rh.add_argument("--record-id", required=True)
    rh.add_argument("--kind", required=True, choices=[
            "claim", "evidence", "tool_run", "session",
        ])
    rh.add_argument("--from-topic", required=True)
    rh.add_argument("--to-topic", required=True)
    rh.add_argument("--reason", required=True)
    rh.add_argument("--operator", default="")
    rh.add_argument("--timestamp", default="")
    rh.add_argument("--dry-run", action="store_true", dest="dry_run")
    rs = rps.add_parser("supersede")
    rs.add_argument("--record-id", required=True)
    rs.add_argument("--kind", required=True, choices=[
            "claim", "evidence", "tool_run", "session",
        ])
    rs.add_argument("--status", required=True, choices=["misrouted", "voided", "superseded", "duplicate"])
    rs.add_argument("--reason", required=True)
    rs.add_argument("--replacement-ref", default="")
    rs.add_argument("--operator", default="")
    rs.add_argument("--timestamp", default="")
    rs.add_argument("--dry-run", action="store_true", dest="dry_run")
    ra = rps.add_parser("audit-routing")
    ra.add_argument("--topic", required=True)
    rl = rps.add_parser("lifecycle")
    rl.add_argument("--record-id", required=True)

_CLI_UNHANDLED = object()

def _dispatch(args: argparse.Namespace) -> dict[str, Any]:
    result = _dispatch_pre_workspace_01(args)
    if result is not _CLI_UNHANDLED:
        return result
    ws = init_workspace(Path(args.base))
    result = _dispatch_workspace_01(args, ws)
    if result is not _CLI_UNHANDLED:
        return result
    result = _dispatch_workspace_02(args, ws)
    if result is not _CLI_UNHANDLED:
        return result
    result = _dispatch_workspace_03(args, ws)
    if result is not _CLI_UNHANDLED:
        return result
    raise SystemExit(f"unsupported command: {args.command}")

def _dispatch_pre_workspace_01(args):
    if args.command == "init":
            return {"ok": True, "workspace_root": str(init_workspace(Path(args.base)).root)}
    if args.command == "record" and args.record_command == "rehome":
            return cmd_record_rehome(args)
    if args.command == "record" and args.record_command == "supersede":
            return cmd_record_supersede(args)
    if args.command == "record" and args.record_command == "audit-routing":
            return cmd_record_audit_routing(args)
    if args.command == "record" and args.record_command == "lifecycle":
            return cmd_record_lifecycle(args)
    if args.command == "adapter" and args.adapter_command in {
            "registry",
            "public-surfaces",
            "bridge-targets",
            "bridge-acceptance",
            "payload-profiles",
            "record-gate-audit",
            "smoke-coverage",
        }:
            return dispatch_adapter_command(args, None)
    if args.command == "query":
            return dispatch_query_command(args)
    if args.command == "context":
            return dispatch_context_command(args)
    return _CLI_UNHANDLED
